<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "slub_zotero"
 *
 * Auto generated by Extension Builder 2019-03-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SLUB: Zotero Bibliografie',
    'description' => 'This extension should call the zotero api and present the SLUB bibliography on the website.',
    'category' => 'plugin',
    'author' => 'Sebastian Semsker',
    'author_email' => 'typo3@slub-dresden.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
